export const testCards = [
  {
    id: "1",
    img: "/image/avatar-5.jpg",
    store: "store2",
    name: "BoB",
    mark: 4,
    category: "Bob",
  },
  {
    id: "2",
    img: "/image/avatar5.png",
    store: "store2",
    name: "Kevin",
    mark: 0,
    category: "Kebin",
  },
  {
    id: "3",
    img: "/image/avatar7.png",
    store: "store4",
    name: "Paradise",
    mark: 5,
    category: "Paradise",
  },
  {
    id: "4",
    img: "/image/avatar8.png",
    store: "store3",
    name: "Harry Potter",
    mark: 2,
    category: "Harry Potter",
  },
  {
    id: "5",
    img: "/image/avatar.png",
    store: "store1",
    name: "Truffle",
    mark: 5,
    category: "Gru",
  },
];
export const popularProducts = [
  {
    id: "1",
    img: "/image/dashboardImg/product1.jpg",
    name: "Bentley",
    category: "car",
  },
  {
    id: "2",
    img: "/image/dashboardImg/product2.jpg",
    name: "Coffee",
    category: "Drink",
  },
  {
    id: "3",
    img: "/image/dashboardImg/product3.jpg",
    name: "Microphone",
    category: "Electronic",
  },
  {
    id: "4",
    img: "/image/dashboardImg/product4.jpg",
    name: "Smart Phone",
    category: "Electronic",
  },
  {
    id: "5",
    img: "/image/dashboardImg/product5.jpg",
    name: "Dot Dog",
    category: "Pet",
  },
];
export const bestStore = [
  {
    id: "1",
    img: "/image/dashboardImg/store1.jpg",
    name: "Store2",
    manager: "Magnolia",
  },
  {
    id: "2",
    img: "/image/dashboardImg/store2.jpg",
    name: "Store3",
    manager: "Truffle",
  },
  {
    id: "3",
    img: "/image/dashboardImg/store3.jpg",
    name: "Store4",
    manager: "Harry Potter",
  },
];

// for product -> allItems main data

export const testCategorys = [
  { id: 1, categoryName: "Bob" },
  { id: 2, categoryName: "Kebin" },
  { id: 3, categoryName: "Stuwart" },
  { id: 4, categoryName: "Gru" },
  { id: 5, categoryName: "Heracles" },
  { id: 6, categoryName: "Paradise" },
];

export const userProfile = {
  userName: "Paradise",
  userEmail: "Paradise@gmail.com",
  userPhoneNumber: "1955048895",
  uerBirthday: "2001-08-09",
  userPassword: "20010809P",
  userAvatar: "/image/prd-img.png",
  totalPayed: "3700",
  createDate: "2024-05-15",
  role: "Admin",
};
export const message = [
  {
    id: "1",
    name: "Karate",
    img: "/image/message.png",
    date: "2024.05.08/13:10",
    contend:
      "This is sasakura Hara This is my first project thak you for giving oppotunity",
  },
  {
    id: "2",
    name: "Karate",
    img: "/image/message.png",
    date: "2024.05.08/13:10",
    contend:
      "This is sasakura Hara This is my first project thak you for giving oppotunity",
  },
  {
    id: "3",
    name: "Karate",
    img: "/image/message.png",
    date: "2024.05.08/13:10",
    contend:
      "This is sasakura Hara This is my first project thak you for giving oppotunity",
  },
  {
    id: "4",
    name: "Karate",
    img: "/image/message.png",
    date: "2024.05.08/13:10",
    contend:
      "This is sasakura Hara This is my first project thak you for giving oppotunity",
  },
  {
    id: "5",
    name: "Karate",
    img: "/image/message.png",
    date: "2024.05.08/13:10",
    contend:
      "This is sasakura Hara This is my first project thak you for giving oppotunity",
  },

  {
    id: "6",
    img: "/image/prd-img.png",
    price: "3200",
    name: "Stuwart",
    mark: 4,
    category: "Stuwart",
  },
  {
    id: "7",
    img: "/image/prd-img.png",
    price: "3200",
    name: "Magnolia",
    mark: 4,
    category: "Bobca",
  },
  {
    id: "8",
    img: "/image/prd-img.png",
    price: "4200",
    name: "Tomato",
    mark: 5,
    category: "Kebin",
  },
  {
    id: "9",
    name: "Karate",
    img: "/image/message.png",
    date: "2024.05.08/13:10",
    contend:
      "This is sasakura Hara This is my first project thak you for giving oppotunity",
  },
];

export const testUserList = [
  {
    id: "fafdsagasgsadgsagsadfsdfsd",
    userName: "paradise",
    userEmail: "Paradise@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/avatar-4.jpg",
    totalPayed: "4000",
    isOnline: true,
    role: "admin",
    permission: true,
  },
  {
    id: "4p98453tjklnmglksgp9ergtewt",
    userName: "Heraclas",
    userEmail: "Heraclas@gmail.com",
    userPhoneNumber: "1912345678",
    uerBirthday: "1999-08-18",
    userAvatar: "/image/avatar-3.jpg",
    totalPayed: "3700",
    isOnline: true,
    role: "user",
    permission: false,
  },
  {
    id: "bvdasjglkaotirp9gvpo",
    userName: "Harry Potter",
    userEmail: "HarryPotter@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/avatar1.png",
    totalPayed: "5000",
    isOnline: false,
    role: "user",
    permission: false,
  },
  {
    id: "fvjou0ewpto4t4p9t43oiutiowhr3r",
    userName: "Magnolia",
    userEmail: "Magnolia@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "1000",
    isOnline: true,
    role: "admin",
    permission: true,
  },
  {
    id: "vnljsp9ewpojmgwgwe",
    userName: "Gru",
    userEmail: "Gru@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "5000",
    isOnline: false,
    role: "user",
    permission: true,
  },
  {
    id: "bjlk4rlkgrge4g",
    userName: "Telamon",
    userEmail: "Telamon@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "2000",
    isOnline: false,
    role: "user",
    permission: false,
  },
  {
    id: "vbjlkjtliewtwrwr",
    userName: "Kolya",
    userEmail: "Kolya@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "2600",
    isOnline: true,
    role: "user",
    permission: true,
  },
  {
    id: "bnmwiuwegerfdslkj",
    userName: "Panda",
    userEmail: "Panda@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "4000",
    isOnline: false,
    role: "user",
    permission: false,
  },
  {
    id: "bnlk4ewpog34opgknwe",
    userName: "Super star",
    userEmail: "Super@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "4000",
    isOnline: true,
    role: "user",
    permission: true,
  },
  {
    id: "bvnklwelkoiupi[ohtro",
    userName: "Haha",
    userEmail: "Haha@gmail.com",
    userPhoneNumber: "1955048895",
    uerBirthday: "2001-08-09",
    userAvatar: "/image/prd-img.png",
    totalPayed: "4000",
    isOnline: true,
    role: "user",
    permission: true,
    img: "/image/prd-img.png",
    price: "30200",
    name: "Harry",
    mark: 5,
    category: "Paradise",
  },
  {
    id: "10",
    img: "/image/prd-img.png",
    price: "3200",
    name: "Star",
    mark: 2,
    category: "Heracles",
  },
  {
    id: "11",
    img: "/image/prd-img.png",
    price: "3200",
    name: "Ronaldo",
    mark: 4,
    category: "Gru",
  },
  {
    id: "12",
    img: "/image/prd-img.png",
    price: "3200",
    name: "Stuwart",
    mark: 4,
    category: "Stuwart",
  },
  {
    id: "13",
    img: "/image/prd-img.png",
    price: "3200",
    name: "scamer",
    mark: 4,
    category: "Bob",
  },
  {
    id: "14",
    img: "/image/prd-img.png",
    price: "4200",
    name: "Kebin",
    mark: 0,
    category: "Kebin",
  },
  {
    id: "15",
    img: "/image/prd-img.png",
    price: "30200",
    name: "panda",
    mark: 5,
    category: "Paradise",
  },
  {
    id: "16",
    img: "/image/prd-img.png",
    price: "3200",
    name: "Heracles",
    mark: 2,
    category: "Gru",
  },
  {
    id: "17",
    img: "/image/prd-img.png",
    price: "3200",
    name: "007",
    mark: 4,
    category: "Gru",
  },
  {
    id: "18",
    img: "/image/prd-img.png",
    price: "3200",
    name: "dev",
    mark: 4,
    category: "Stuwart",
  },
  {
    id: "19",
    img: "/image/prd-img.png",
    price: "320",
    name: "ruci",
    mark: 0,
    category: "Stuwart",
  },
  {
    id: "20",
    img: "/image/prd-img.png",
    price: "3200",
    name: "dev",
    mark: 4,
    category: "Stuwart",
  },
  {
    id: "21",
    img: "/image/prd-img.png",
    price: "320",
    name: "ruci",
    mark: 0,
    category: "Stuwart",
  },
  {
    id: "22",
    img: "/image/prd-img.png",
    price: "3200",
    name: "scamer",
    mark: 4,
    category: "Bob",
  },
  {
    id: "23",
    img: "/image/prd-img.png",
    price: "4200",
    name: "Kebin",
    mark: 0,
    category: "Kebin",
  },
  {
    id: "24",
    img: "/image/prd-img.png",
    price: "30200",
    name: "panda",
    mark: 3,
    category: "Paradise",
  },
];

export const inventory = [
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Kevin",
    category: "Lucy",
    description: "something else",
    price: "$ 2300",
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Bob",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "This is good",
    price: "$ 5600",
    total: "67",
    sold: "17",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/message.png",
    name: "Kervin",
    category: "Bob",
    description: "This is good.",
    price: "$ 2300",
    total: "120",
    sold: "70",
    remain: "50",
  },
];

// for product -> allItems main data
export const PRODUCT_ALL_ITEMS = [
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 2,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 'ewrwewfwr23fw',
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 'asfqwffwefwfsdfebshra',
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
  {
    id: 1,
    thumbnail: "/image/prd-img.png",
    name: "Bob",
    category: "Gru",
    description: "something else",
    price: 2300,
    total: "60",
    sold: "12",
    remain: "48",
  },
];
export const productData = [
  {
    id: "1",
    name: "Potato",
    category: "vegitable",
    description: "health",
    price: "310",
    quantity: "900",
    discount: "10",
    sold: "47",
    img: "/image/gru.png",
  },
  {
    id: "2",
    name: "apple",
    category: "vegitable",
    description: "health",
    price: "30",
    quantity: "900",
    discount: "10",
    sold: "47",
    img: "/image/gru.png",
  },
  {
    id: "3",
    name: "onion",
    category: "vegitable",
    description: "health",
    price: "38",
    quantity: "90",
    discount: "10",
    sold: "47",
    img: "/image/gru.png",
  },
  {
    id: "4",
    name: "banana",
    category: "vegitable",
    description: "health",
    price: "549",
    quantity: "900",
    discount: "10",
    sold: "47",
    img: "/image/gru.png",
  },
  {
    id: "5",
    name: "pair",
    category: "vegitable",
    description: "health",
    price: "982",
    quantity: "900",
    discount: "10",
    sold: "47",
    img: "/image/gru.png",
  },
];

export const testStoreList = [
  {
    id: 1,
    store: "Astore",
  },

  {
    id: 2,
    store: "Bstore",
  },
  {
    id: 3,
    store: "Cstore",
  },
  {
    id: 4,
    store: "Dstore",
  },
];
export const STORE_ALL_ITEMS = [
  {
    id: 1,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 2,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 3,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 4,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 5,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 6,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 7,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 8,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 9,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 10,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 11,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 12,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 13,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 14,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 15,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 16,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 17,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 18,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 19,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 20,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 21,
    avatar: "/image/prd-img.png",
    name: "Kevin",
    earned: "$ 2300",
    users: "12",
  },
  {
    id: 22,
    avatar: "/image/message.png",
    name: "Bob",
    earned: "$ 2300",
    users: "70",
  },
  {
    id: 23,
    avatar: "/image/prd-img.png",
    name: "Bob",
    earned: "$ 5600",
    users: "17",
  },
  {
    id: 24,
    avatar: "/image/message.png",
    name: "Kervin",
    earned: "$ 2300",
    users: "70",
  },
];
